### ISSUE TITLE
feedback.html

### ISSUE THREAD

**Issue by guledali** [octogroup/octogroup.github.io#40]
Make feedback.html page look more like this

![screenshot 9 _li](https://user-images.githubusercontent.com/20647282/32326574-9a1243b6-bfd3-11e7-9202-cfd37821bcd5.jpg)

Then 
![screenshot 10](https://user-images.githubusercontent.com/20647282/32326597-b284579a-bfd3-11e7-954e-f80c110aed9f.png)

**Comment by mirandamutka** [comment]
Look over the first question, should say "kursen" instead of "kurser"
