### ISSUE TITLE
Närvaro ASDF does not work on an actual mobile phone

### ISSUE THREAD

**Issue by Svahnen** [octogroup/octogroup.github.io#90]

**Comment by Svahnen** [comment]
May have to do with mobile characters not being entered as a string or something simmular happening (a possible workaround may be, using == instead of ===)

**Comment by rawnney** [comment]
Or it might have to do something with texttransform uppercase, haven’ttried it out.

**Comment by rawnney** [comment]
solved in ce3dd79
